### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by jhe01** [devconcept/multer-gridfs-storage#16]
I am having an error in starting my app.

see below:

> { MongoError: Authentication failed.
    at /var/www/app-api/node_modules/mongodb-core/lib/connection/pool.js:581:63
    at authenticateStragglers (/var/www/app-api/node_modules/mongodb-core/lib/connection/pool.js:504:16)
    at Connection.messageHandler (/var/www/app-api/node_modules/mongodb-core/lib/connection/pool.js:540:5)
    at emitMessageHandler (/var/www/app-api/node_modules/mongodb-core/lib/connection/connection.js:310:10)
    at Socket.<anonymous> (/var/www/app-api/node_modules/mongodb-core/lib/connection/connection.js:453:17)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
  ok: 0,
  errmsg: 'Authentication failed.',
  code: 18,
  codeName: 'AuthenticationFailed',
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} }
(node:20192) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'db' of undefined
    at Object.getDatabase (/var/www/app-api/node_modules/multer-gridfs-storage/lib/utils.js:187:11)
    at GridFSStorage._setDb (/var/www/app-api/node_modules/multer-gridfs-storage/lib/gridfs.js:238:19)
    at promise.then (/var/www/app-api/node_modules/multer-gridfs-storage/lib/gridfs.js:173:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:20192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

i am using

multer-gridfs-storage: ^3.2.3
mongodb: 4.0.4
multer: ^1.4.1
gridfs-stream: ^1.1.1

In my laptop i don't have this kind of problem. but after i upload it to ubuntu 18.0 virtual machine. the error occurred.

Please i need help.

Thank you in advance!

**Comment by devconcept** [comment]
This seems to be more a problem with your production environment than with the library itself because as you said it works in your development machine however without more info it is impossible to understand your problem.

Are you using urls or database objects to connect? Are you caching connections or not?

You can't be using mongodb version `4.0.4` because it currently is at version [`3.1.9`](https://github.com/mongodb/node-mongodb-native/blob/c0e648c46318cca5556ca18e27a9be26a7bcde71/package.json#L3). Please update the correct version in your issue.

**Comment by jhe01** [comment]
@devconcept 

thank you for your response.

i follow this instructions to install mongodb in ubuntu

https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/

and also i can't seem to find a way how to install version 3.1.9 ..i tried to change this 

echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list

to this 

echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.1 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.1.list

but on apt-get update it prompts that it doesn't have that package or something ..

do you know how to install mongodb version 3.1.9 in ubuntu 16.04?

**Comment by devconcept** [comment]
When I asked the mongodb version I was talking about the [mongodb driver](https://github.com/mongodb/node-mongodb-native/) node module, not the mongodb program installed in your system.

At some point you had to write `npm install mongodb --save` and you got mongodb for node installed in your project. This is the version that is relevant to this module.

**Comment by jhe01** [comment]
@devconcept 

Sorry for misunderstanding.

I didn't include that i used mongoose to connect to mongodb.
